name: Prerender - Create bulk prerenders from gist

on:
  workflow_dispatch:
    inputs:
      gist:
        description: 'GitHub gist with URLs to prerender'
        required: true
        type: string
      network:
        description: 'Network to write to'
        required: true
        type: choice
        options:
          - staging
          - production
      namespace:
        description: 'Namespace to write to'
        required: true
        type: choice
        options:
          - stage
          - prod
      group:
        description: 'Group to write to'
        required: true
        type: string
        default: 'frictionless'

jobs:
  create-prerenders:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools/prerender/prerender.js
            tools/prerender/prerender-gist.js
            package-lock.json
            package.json

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}-${{ runner.os }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Setup Akamai Authentication
        env:
          EDGERC: ${{ secrets.EDGERC_EDGEKV }}
        run: |
          echo "${EDGERC}" > ~/.edgerc

      - name: Process gist and create prerenders
        run: |
          node tools/prerender/prerender-gist.js "${{ inputs.gist }}" "${{ inputs.network }}" "${{ inputs.namespace }}" "${{ inputs.group }}"
        env:
          USER_AGENT_SUFFIX: ${{ secrets.USER_AGENT_SUFFIX }}

      - name: Cleanup Akamai credentials
        if: always()
        run: rm -f ~/.edgerc   